# permissions for end users to view applicationprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationprofile-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lb
    app.kubernetes.io/part-of: lb
    app.kubernetes.io/managed-by: kustomize
  name: applicationprofile-viewer-role
rules:
- apiGroups:
  - lb.my.domain
  resources:
  - applicationprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lb.my.domain
  resources:
  - applicationprofiles/status
  verbs:
  - get
