apiVersion: lb.my.domain/v1
kind: NIC
metadata:
  labels:
    app.kubernetes.io/name: nic
    app.kubernetes.io/instance: nic-sample
    app.kubernetes.io/part-of: lb
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lb
  name: nic-sample
spec:
  # TODO(user): Add fields here
