apiVersion: lb.my.domain/v1
kind: Monitor
metadata:
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/instance: monitor-sample
    app.kubernetes.io/part-of: lb
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lb
  name: monitor-sample
spec:
  # TODO(user): Add fields here
