apiVersion: lb.my.domain/v1
kind: VirtualServer
metadata:
  labels:
    app.kubernetes.io/name: virtualserver
    app.kubernetes.io/instance: virtualserver-sample
    app.kubernetes.io/part-of: lb
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: lb
  name: virtualserver-sample
spec:
  enabled: true
  protocol: l4
  virtual_network:
    namespace: default
    name: vn1
  port: 80
  default_server_pool:
    namespace: default
    name: sp1
  application_profile:
    namespace: default
    name: app1
