# permissions for end users to edit lbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lb-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lb
    app.kubernetes.io/part-of: lb
    app.kubernetes.io/managed-by: kustomize
  name: lb-editor-role
rules:
- apiGroups:
  - lb.my.domain
  resources:
  - lbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lb.my.domain
  resources:
  - lbs/status
  verbs:
  - get
